### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by charlieduong94** [CharlesWall/waitForEvent#1]
![giphy](https://user-images.githubusercontent.com/9613701/29745463-0347b8be-8a89-11e7-96f8-082892ca55b5.gif)

**Comment by Epitrochoid** [comment]
![slkdjflskjf](http://0.media.collegehumor.cvcdn.com/77/65/175eb3b65a7c3ebc3195379c653d61b6-hansgiving-why-were-thankful-for-tom-hanks.jpg)
